# Generated by Django 2.2.4 on 2021-04-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0002_auto_20210423_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name_prefix',
            new_name='salutation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
