# Generated by Django 3.1.5 on 2021-02-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('primary_email', models.CharField(max_length=100)),
                ('secondary_email', models.CharField(max_length=100)),
                ('address', models.CharField(default=None, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
                ('created_date', models.DateField(auto_now=True)),
                ('modified_date', models.DateField(auto_now_add=True)),
                ('promotional_emails', models.BooleanField(default=False, null=True)),
                ('transactional_emails', models.BooleanField(default=False, null=True)),
                ('promotional_sms', models.BooleanField(default=False, null=True)),
                ('transactional_sms', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Buy'), ('B', 'Sell')], max_length=1)),
                ('date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.customer')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.stock')),
            ],
        ),
    ]
